"""prompt added

Revision ID: 54c72769cdf4
Revises: 865ad6d46a4f
Create Date: 2024-05-02 15:40:43.024120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c72769cdf4'
down_revision = '865ad6d46a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Polls', schema=None) as batch_op:
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
