"""added tags and date for polls

Revision ID: 865ad6d46a4f
Revises: eeb3759c7d62
Create Date: 2024-05-02 11:34:50.415516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865ad6d46a4f'
down_revision = 'eeb3759c7d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tag2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tag3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Polls', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('tag3')
        batch_op.drop_column('tag2')
        batch_op.drop_column('tag1')

    # ### end Alembic commands ###
